apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: techtrends
    spec:
      containers:
        - image: m7moxd/techtrends:latest
          imagePullPolicy: IfNotPresent
          name: techtrends
          ports:
            - containerPort: 3111
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /heathz
              port: 3111
          readinessProbe:
            httpGet:
              path: /heathz
              port: 3111
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'
