apiVersion: v1
name: techtrends
description: Cloud Native Application Architecture - TechTrends Project
keywords:
  - techtrends
version: 1.0.0
maintainers:
  - name: 'Mahmoud Shehab'
    email: mahmood.x.mostafa@gmail.com
